[package]
name = "soytrie"
version = "0.1.0"
edition = "2021"
authors = ["Prem Phansuriyanon"]
description = "A generic trie implementation using Rust's HashMap"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
